[project]
name = "topicos-ia-2do-parcial-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dspy>=3.0.3",
    "fastapi[standard]>=0.120.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
]
